version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 
      - bash
      - -c
      - npm install && npm start
    #env_file:
    #  - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    restart: on-failure
